### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26x0

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/ct/Makefile.ct

BOARD_SOURCEFILES += board.c leds-arch.c

CONTIKI_TARGET_DIRS += ct/waveform
